@startuml

rectangle 买家 as customer
rectangle 收货地址 as contact
rectangle 购物车记录 as shopCar

customer -right- contact : 1:n
customer -left- shopCar : n:1

customer -up-- (买家id)
customer -up-- (手机号)
customer -up-- (密码)
customer --- (姓名)
customer --- (昵称)
customer --- (性别)
customer --- (头像)

contact -up- (收货地址id)
contact -up- (联系人姓名)
contact -- (联系人电话)
contact -- (收货地址)

shopCar -up- (购物车记录id)
shopCar -left- (商品id)
shopCar -- (购买数量)

@enduml