@startuml

title 买家购买商品活动图

(*) -> 查询商品
-> 查看商品详情
-> 选择数量
选择数量 --> 确认购买
选择数量 --> 加入购物车
加入购物车 --> 确认购买
-left-> 填写收货地址
-left-> 留言备注
--> 下单
-right-> [收到卖家发的货] 确认收货
--> 评价订单
--> (*)

下单 --> 申请退款
--> (*)

@enduml