@startuml

left to right direction

:买家:
买家 --> (注册)
买家 --> (登录)
买家 --> (修改个人信息)
买家 --> (注册商店)
买家 --> (修改商店信息)
买家 --> (删除商店)
买家 --> (添加商品)
买家 --> (修改商品信息)
买家 --> (删除商品)
买家 --> (管理订单)

修改商品信息 <.. (查询商品) : <<include>>
删除商品 <.. (查询商品) : <<include>>

修改商店信息 <.. (查询商店) : <<include>>
删除商店 <.. (查询商店) : <<include>>

管理订单 <.. (确认发货) : <<extend>>
管理订单 <.. (确认退款) : <<extend>>

@enduml