@startuml

left to right direction

:买家:
买家 --> (注册)
买家 --> (登录)
买家 --> (修改个人信息)
买家 --> (查看商品详情)
买家 --> (下单)
买家 --> (确认收货)
买家 --> (评价订单)
买家 --> (申请退款)

查看商品详情 <.. (查询商品) : <<include>>
查看商品详情 <.. (查看用户评价) : <<extend>>
下单 <.. (添加到购物车) : <<extend>>
下单 <.. (填写收货地址) : <<include>>
确认收货 <.. (查询订单) : <<include>>
申请退款 <.. (查询订单) : <<include>>
评价订单 <.. (查询订单) : <<include>>

@enduml