@startuml

usecase 顾客 as c
usecase 订单 as o
usecase 商品 as g

c -right-> o : 1:n
g -left-> o : 1:n

(顾客id) --> c
(姓名) -> c
(性别) -up-> c

(创建日期) -up-> o
(收货地址) -up-> o
(商品数量) --> o
(总价) --> o

(商品id) --> g
(商品名称) --> g
(单价) -left-> g
(商品描述) -up-> g

@enduml