@startuml

actor 顾客 as customer
participant 页面 as view
control 业务层和持久层 as sc

customer -> view : 输入关键字搜索
view     -> sc   : 根据关键字查询商品
sc       -> view : 返回商品列表
customer <- view : 显示商品列表

customer -> view : 点击某一个商品
view     -> sc   : 根据商品id查询商品详情
sc       -> view : 返回商品详细信息
customer <- view : 显示商品详细信息

customer -> view : 选择商品颜色并加入购物车
view     -> sc   : 添加购物车记录
sc       -> view : 添加成功提示
customer <- view : 提示添加成功

customer -> view : 选择商品颜色并提交订单
customer <- view : 提示是否立即付款
view     -> sc   : 提交订单
sc       -> view : 返回订单详细信息
customer <- view : 显示订单详细信息

@enduml