@startuml

state "Created：订单已创建，等待商家发货" as Created
state "Pending_Receive：商家已发货，顾客等待收货" as Pending_Receive
state "Received：顾客已经收货" as Received
state "Pending_Return_Money：顾客申请退款，等待商家退款" as Pending_Return_Money
state "Finish：订单结束" as Finish

[*] --> Created : 顾客下单
Created --> Pending_Receive : 商家发货
Created -right-> Pending_Return_Money : 顾客申请退款
Pending_Receive --> Pending_Return_Money : 顾客申请退款
Pending_Receive --> Received : 顾客确认收货
Received --> Pending_Return_Money : 顾客申请退款

Pending_Return_Money --> Finish : 商家退款
Received --> Finish : 顾客评价

Finish --> [*]

@enduml